# Push Notification Setup Script
# This script helps configure push notifications for the employee portal

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "  Push Notification Setup for Employee Portal" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host ""

# Check if web-push is installed
Write-Host "Checking dependencies..." -ForegroundColor Yellow
$packageJson = Get-Content -Path "package.json" -Raw | ConvertFrom-Json

if (-not ($packageJson.dependencies.'web-push' -or $packageJson.devDependencies.'web-push')) {
    Write-Host "Installing web-push package..." -ForegroundColor Yellow
    npm install web-push
    npm install --save-dev @types/web-push
    Write-Host "✓ Dependencies installed" -ForegroundColor Green
} else {
    Write-Host "✓ web-push already installed" -ForegroundColor Green
}

Write-Host ""

# Generate VAPID keys
Write-Host "Generating VAPID keys..." -ForegroundColor Yellow
$vapidOutput = npx web-push generate-vapid-keys 2>&1

# Parse the output
$publicKey = ""
$privateKey = ""

foreach ($line in $vapidOutput) {
    if ($line -match "Public Key:\s*(.+)") {
        $publicKey = $matches[1].Trim()
    }
    if ($line -match "Private Key:\s*(.+)") {
        $privateKey = $matches[1].Trim()
    }
}

Write-Host "✓ VAPID keys generated" -ForegroundColor Green
Write-Host ""

# Generate CRON_SECRET
Write-Host "Generating CRON_SECRET..." -ForegroundColor Yellow
$cronSecret = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 32 | ForEach-Object {[char]$_})
Write-Host "✓ CRON_SECRET generated" -ForegroundColor Green
Write-Host ""

# Create or update .env.local
Write-Host "Updating .env.local file..." -ForegroundColor Yellow

$envContent = @"

# ===== PUSH NOTIFICATIONS =====
# Generated by setup-notifications.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# VAPID Keys (for web push notifications)
NEXT_PUBLIC_VAPID_PUBLIC_KEY=$publicKey
VAPID_PRIVATE_KEY=$privateKey
VAPID_EMAIL=mailto:admin@anuranan.com

# Cron Job Security
CRON_SECRET=$cronSecret

# Site URL (update this after deployment)
NEXT_PUBLIC_SITE_URL=http://localhost:3000
"@

if (Test-Path ".env.local") {
    # Check if push notification config already exists
    $existingContent = Get-Content -Path ".env.local" -Raw
    
    if ($existingContent -match "VAPID") {
        Write-Host "⚠ Push notification variables already exist in .env.local" -ForegroundColor Yellow
        $overwrite = Read-Host "Do you want to overwrite them? (y/N)"
        
        if ($overwrite -eq 'y' -or $overwrite -eq 'Y') {
            # Remove old push notification config
            $existingContent = $existingContent -replace "(?ms)# ===== PUSH NOTIFICATIONS =====.*?(?=# =====|\z)", ""
            $existingContent = $existingContent -replace "NEXT_PUBLIC_VAPID_PUBLIC_KEY=.*`n?", ""
            $existingContent = $existingContent -replace "VAPID_PRIVATE_KEY=.*`n?", ""
            $existingContent = $existingContent -replace "VAPID_EMAIL=.*`n?", ""
            $existingContent = $existingContent -replace "CRON_SECRET=.*`n?", ""
            
            Set-Content -Path ".env.local" -Value ($existingContent.TrimEnd() + $envContent)
            Write-Host "✓ .env.local updated with new keys" -ForegroundColor Green
        } else {
            Write-Host "⊘ Skipped updating .env.local" -ForegroundColor Yellow
        }
    } else {
        Add-Content -Path ".env.local" -Value $envContent
        Write-Host "✓ .env.local updated" -ForegroundColor Green
    }
} else {
    Set-Content -Path ".env.local" -Value $envContent.TrimStart()
    Write-Host "✓ .env.local created" -ForegroundColor Green
}

Write-Host ""
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "  Setup Complete!" -ForegroundColor Green
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "Next Steps:" -ForegroundColor Yellow
Write-Host ""
Write-Host "1. Run the database migration:" -ForegroundColor White
Write-Host "   - Go to Supabase Dashboard → SQL Editor" -ForegroundColor Gray
Write-Host "   - Run the SQL in: supabase/push-subscriptions.sql" -ForegroundColor Gray
Write-Host ""
Write-Host "2. Update NEXT_PUBLIC_SITE_URL in .env.local:" -ForegroundColor White
Write-Host "   - After deployment, set it to your production URL" -ForegroundColor Gray
Write-Host "   - Example: https://your-app.netlify.app" -ForegroundColor Gray
Write-Host ""
Write-Host "3. Set up the cron job:" -ForegroundColor White
Write-Host "   - For Netlify: Create a scheduled function" -ForegroundColor Gray
Write-Host "   - For Vercel: Add cron config to vercel.json" -ForegroundColor Gray
Write-Host "   - See PUSH_NOTIFICATIONS_SETUP.md for details" -ForegroundColor Gray
Write-Host ""
Write-Host "4. Add environment variables to your deployment platform:" -ForegroundColor White
Write-Host "   - NEXT_PUBLIC_VAPID_PUBLIC_KEY" -ForegroundColor Gray
Write-Host "   - VAPID_PRIVATE_KEY" -ForegroundColor Gray
Write-Host "   - VAPID_EMAIL" -ForegroundColor Gray
Write-Host "   - CRON_SECRET" -ForegroundColor Gray
Write-Host "   - NEXT_PUBLIC_SITE_URL" -ForegroundColor Gray
Write-Host ""
Write-Host "5. Test the setup:" -ForegroundColor White
Write-Host "   - Run: npm run dev" -ForegroundColor Gray
Write-Host "   - Visit http://localhost:3000" -ForegroundColor Gray
Write-Host "   - Enable notifications when prompted" -ForegroundColor Gray
Write-Host ""
Write-Host "For detailed instructions, see:" -ForegroundColor Yellow
Write-Host "  PUSH_NOTIFICATIONS_SETUP.md" -ForegroundColor Cyan
Write-Host ""
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host ""

# Display the generated values
Write-Host "Generated Configuration:" -ForegroundColor Yellow
Write-Host "------------------------" -ForegroundColor Gray
Write-Host "Public Key:  $publicKey" -ForegroundColor White
Write-Host "Private Key: $($privateKey.Substring(0, 20))..." -ForegroundColor White
Write-Host "CRON Secret: $($cronSecret.Substring(0, 16))..." -ForegroundColor White
Write-Host ""
Write-Host "⚠ Keep the Private Key and CRON Secret secure!" -ForegroundColor Red
Write-Host ""
